export const LoginActionTypes = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  SEND_MAIL_VERIFICATION_FOR_SIGNUP: 'SEND_MAIL_VERIFICATION_FOR_SIGNUP',
  SEND_MAIL_VERIFICATION_FOR_SIGNUP_SUCCESS: 'SEND_MAIL_VERIFICATION_FOR_SIGNUP_SUCCESS',
  SEND_MAIL_VERIFICATION_FOR_SIGNUP_FAILED: 'SEND_MAIL_VERIFICATION_FOR_SIGNUP_FAILED',
  SIGNUP: 'SIGNUP',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILED: 'SIGNUP_FAILED'
};
